---

# https://docs.ansible.com/ansible/latest/modules/group_module.html
- name: Configure group(s)
  group:
    gid: '{{ item.gid | default(omit) }}'
    local: '{{ item.local | default(omit) }}'  # default: no
    name: '{{ item.name }}'  # required!!!
    state: '{{ item.state | default(omit) }}'  # default: present
    system: '{{ item.system | default(omit) }}'  # default: no
  loop: '{{ delta_groups }}'

# https://docs.ansible.com/ansible/latest/modules/user_module.html
- name: Configure user(s)
  user:
    append: '{{ item.append | default(omit) }}'  # default: no
    comment: '{{ item.comment | default(omit) }}'
    create_home: '{{ item.create_home | default(omit) }}'  # default: yes
    expires: '{{ item.expires | default(omit) }}'
    force: '{{ item.force | default(omit) }}'  # default: no
    generate_ssh_key: '{{ item.generate_ssh_key | default(omit) }}'  # default: no
    group: '{{ item.group | default(omit) }}'
    groups: '{{ item.groups | default(omit) }}'
    hidden: '{{ item.hidden | default(omit) }}'  # default: yes, if system
    home: '{{ item.home | default(omit) }}'
    local: '{{ item.local | default(omit) }}'  # default: no
    login_class: '{{ item.login_class | default(omit) }}'
    move_home: '{{ item.move_home | default(omit) }}'  # default: no
    name: '{{ item.name }}'  # required!!!
    non_unique: '{{ item.non_unique | default(omit) }}'  # default: no
    password: '{{ item.password | default(omit) }}'
    password_lock: '{{ item.password_lock | default(omit) }}'  # default: no???
    remove: '{{ item.remove | default(omit) }}'  # default: no
    seuser: '{{ item.seuser | default(omit) }}'
    shell: '{{ item.shell | default(omit) }}'
    skeleton: '{{ item.skeleton | default(omit) }}'  # requires create_home
    ssh_key_bits: '{{ item.ssh_key_bits | default(omit) }}'  # default: default set by ssh-keygen
    ssh_key_comment: '{{ item.ssh_key_comment | default(omit) }}'  # default: ansible-generated on $HOSTNAME
    ssh_key_file: '{{ item.ssh_key_file | default(omit) }}'  # default: .ssh/id_rsa
    ssh_key_passphrase: '{{ item.ssh_key_passphrase | default(omit) }}'
    ssh_key_type: '{{ item.ssh_key_type | default(omit) }}'  # default: rsa
    state: '{{ item.state | default(omit) }}'  # default: present
    system: '{{ item.system | default(omit) }}'  # default: no
    uid: '{{ item.uid | default(omit) }}'
    update_password: '{{ item.update_password | default(omit) }}'  # default: always
  loop: '{{ delta_users }}'

# https://docs.ansible.com/ansible/latest/modules/authorized_key_module.html
- name: Configure authorized key(s)
  authorized_key:
    comment: '{{ item.comment | default(omit) }}'
    exclusive: '{{ item.exclusive | default(omit) }}'  # default: no
    key: '{{ item.key }}'  # required!!!
    key_options: '{{ item.key_options | default(omit) }}'
    manage_dir: '{{ item.manage_dir | default(omit) }}'  # default: yes
    path: '{{ item.path | default(omit) }}'  # default: (homedir)+/.ssh/authorized_keys
    state: '{{ item.state | default(omit) }}'  # default: present
    user: '{{ item.user }}'  # required!!!
    validate_certs: '{{ item.validate_certs | default(omit) }}'  # default: yes
  loop: '{{ delta_authorized_keys }}'

# https://docs.ansible.com/ansible/latest/modules/blockinfile_module.html
- name: Configure sudoer(s)
  blockinfile:
    attributes: '{{ item.attributes | default(omit) }}'
    backup: '{{ item.backup | default(omit) }}'  # default: no
    block: '{{ item.block | default(omit) }}'
    create: '{{ item.create | default(omit) }}'  # default: no
    group: '{{ item.group | default(omit) }}'
    insertafter: '{{ item.insertafter | default(omit) }}'  # default: EOF
    insertbefore: '{{ item.insertbefore | default(omit) }}'  # default: BOF???
    marker: '{{ item.marker | default(omit) }}'  # default: # {mark} ANSIBLE MANAGED BLOCK
    marker_begin: '{{ item.marker_begin | default(omit) }}'  # default: BEGIN
    marker_end: '{{ item.marker_end | default(omit) }}'  # default: END
    mode: '{{ item.mode | default(omit) }}'
    owner: '{{ item.owner | default(omit) }}'
    path: '{{ item.path }}'  # required!!!
    selevel: '{{ item.selevel | default(omit) }}'  # default: s0
    serole: '{{ item.serole | default(omit) }}'
    setype: '{{ item.setype | default(omit) }}'
    seuser: '{{ item.seuser | default(omit) }}'
    state: '{{ item.state | default(omit) }}'  # default: present
    unsafe_writes: '{{ item.unsafe_writes | default(omit) }}'  # default: no
    validate: '{{ item.validate | default(omit) }}'
  loop: '{{ delta_sudoers }}'
